"""empty message

Revision ID: 041ccfeed1d3
Revises: 33f109788c49
Create Date: 2020-01-16 20:39:31.214760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '041ccfeed1d3'
down_revision = '33f109788c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
