"""empty message

Revision ID: 322b81ecedf0
Revises: 
Create Date: 2020-01-16 19:42:45.314577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322b81ecedf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=84), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lighting_type', sa.String(length=20), nullable=True),
    sa.Column('minimum_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('maximum_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('total_buttons', sa.Integer(), nullable=True),
    sa.Column('total_programmable_buttons', sa.Integer(), nullable=True),
    sa.Column('wireless', sa.Boolean(), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('width', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=62), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('staff', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=84), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('specifications_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['product_brands.id'], ),
    sa.ForeignKeyConstraint(['specifications_id'], ['product_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_and_feature_assoc',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_feature_id'], ['product_features.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('product_and_tag_assoc',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_tag_id'], ['product_tags.id'], )
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=120), nullable=False),
    sa.Column('main', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_table('product_and_tag_assoc')
    op.drop_table('product_and_feature_assoc')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('product_tags')
    op.drop_table('product_specifications')
    op.drop_table('product_features')
    op.drop_table('product_brands')
    # ### end Alembic commands ###
